META = {
    "70B3D57050001AB9": {
        "name": "Pikkukosken uimaranta",
        "location": "Pikkukoski",
        "district": "Veräjämäki",
        "lat": 60.227704,
        "lon": 24.983821,
        "servicemap_url": "https://palvelukartta.hel.fi/unit/41960",
        "site_url": "",
        "links": {},
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D57050001BBE": {
        "name": "Rastilan uimaranta",
        "location": "Vartiokylänlahti",
        "district": "Rastila",
        "lat": 60.207977,
        "lon": 25.114849,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40157",
        "site_url": "https://www.kuhat.com/talviuinti/",
        "site_title": "Uintiseura Kuhat Ry",
        "links": {},
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D5705000E418": {
        "name": "Sompasauna",
        "location": "Hermanninranta",
        "district": "Hermanni",
        "lat": 60.194102,
        "lon": 24.984992,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/54929",
        "site_url": "https://www.sompasauna.fi/",
        "site_title": "Sompasauna Ry",
        "links": {},
        "valid_from": "2022-05-05T16:00:00Z",
        "properties": {
            "installation depth": -0.39,  # Changed 2022-0907 -0.28 -> -0.39
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    "70B3D5705000DFF6": {
        "name": "Munkkiniemen uimaranta",
        "location": "Laajalahti",
        "district": "Munkkiniemi (Vanha Munkkiniemi)",
        "lat": 60.200333,
        "lon": 24.857306,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/41601",
        "site_url": "",
        "site_title": "",
        "valid_from": "2022-05-13T13:00:00Z",
        "properties": {
            "installation depth": -0.3,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    "70B3D5705000DFED": {
        "name": "Katajanokan mattolaituri",
        "location": "Laivastopuisto",
        "district": "Katajanokka",
        "lat": 60.169316,
        "lon": 24.976013,
        "servicemap_url": "",
        "site_url": "",
        "site_title": "",
        "valid_from": "2022-06-13T14:00:00Z",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D5705000E3C0": {
        "name": "Rajasaari",
        "location": "Humalluodot",
        "district": "Taka-Töölö",
        "lat": 60.180667,
        "lon": 24.908639,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40606",
        "site_url": "http://hkk-talviuimarit.fi/",
        "site_title": "HKK-Talviuimarit",
        "valid_from": "2022-05-13T13:00:00Z",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D57050004D86": {
        "name": "Pihlajasaari",
        "location": "Retkisatama",
        "district": "Ulkosaaret (Länsisaaret)",
        "lat": 60.140588,
        "lon": 24.9157002,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/41977",
        "site_url": "",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D57050004FB9": {
        "name": "Hietaniemi",
        "location": "Ourit",
        "district": "Etu-Töölö",
        "lat": 60.1715,
        "lon": 24.8983,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40142",
        "site_url": "http://www.tuk.fi",
        "site_title": "Talviuimarienkerho ry",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    # "70B3D57050004DF8": {
    #     "name": "Vasikkasaari (Helsinki)",
    #     "lat": 60.15232,
    #     "lon": 25.01586,
    #     "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/50903",
    #     "site_url": "https://www.vasikkasaari.org",
    # },
    #    '70B3D57050004FE1': {
    #        'name': 'Herttoniemi (Tuorinniemen uimalaituri)',
    #        'lat': 60.18554,
    #        'lon': 25.04012,
    #        'servicemap_url': 'https://palvelukartta.hel.fi/fi/unit/41791',
    #        'site_url': '',
    #    },
    "70B3D5705000E430": {
        "name": "Tuorinniemi",
        "location": "Kaivolahti",
        "district": "Herttoniemi (Herttoniemenranta)",
        "lat": 60.18554,
        "lon": 25.04012,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/41791",
        "site_url": "",
        "valid_from": "2022-05-30T13:00:00Z",
        "properties": {
            "installation depth": -0.3,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    "70B3D5705000E070": {
        "name": "Matosaari itä",
        "location": "Villinginsalmi",
        "district": "Laajasalo (Jollas)",
        "lat": 60.156914,
        "lon": 25.082887,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40798",
        "site_url": "",
        "valid_from": "2022-06-05T10:00:00Z",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D5705000E3EF": {
        "name": "Matosaari länsi",
        "location": "Jollaksenlahti",
        "district": "Laajasalo (Jollas)",
        "lat": 60.156126,
        "lon": 25.081486,
        "servicemap_url": "",
        "site_url": "",
        "valid_from": "2022-06-05T10:00:00Z",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D5705000E3B2": {
        "name": "Reposalmi VK",
        "location": "Reposalmi",
        "district": "Laajasalo (Yliskylä)",
        "lat": 60.18052,
        "lon": 25.06532,
        "servicemap_url": "",
        "site_url": "",
        "valid_from": "2022-07-04T17:00:00Z",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    # "70B3D57050004FE6": {
    #     "name": "Vartiosaari (Reposalmen laituri)",
    #     "district": "Vartiosaari",
    #     "lat": 60.18010,
    #     "lon": 25.06860,
    #     "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/57156",
    #     "site_url": "https://www.vartiosaari.fi",
    # },
    "70B3D57050004E0E": {
        "name": "Marjaniemen uimaranta",
        "location": "",
        "district": "Vartiokylä (Marjaniemi)",
        "lat": 60.198449,
        "lon": 25.076416,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40386",
        "site_url": "http://www.meriuimarit.fi/",
        "site_title": "Meriuimarit ry",
        "properties": {
            "installation depth": -0.3,
            "installation platform": "wall",
            "installation method": "static",
        },
    },
    "70B3D5705000504F": {
        "name": "Hanikan uimaranta",
        "location": "Suinonsalmi",
        "district": "Espoo (Soukka)",
        "lat": 60.127797,
        "lon": 24.691871,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/39583",
        "site_url": "",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D57050001BA6": {
        "name": "Vetokannas",
        "location": "Silvola",
        "district": "Vantaa (Kaivoksela)",
        "lat": 60.27026,
        "lon": 24.88056,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/42505",
        "site_url": "",
        "info": "Alhaisen vedenpinnan johdosta sensori mittasi ilman lämpötilaa 6.-23.8.2022.",
        "fieldmap": {
            "temp_water": "temp_out1",
            "air_rh": "temprh_rh",
            "air_temp": "temprh_temp",
        },
        "properties": {
            "installation depth": -0.3,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    "70B3D57050001ADA": {
        "name": "Kuusijärvi",
        "location": "Uimaranta",
        "district": "Vantaa (Kuninkaanmäki)",
        "lat": 60.313343,
        "lon": 25.113967,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/42611",
        "site_url": "https://www.vantaa.fi/vapaa-aika/luonto_ja_ulkoilu/retkeily/kuusijarven_ulkoilualue",
        "fieldmap": {
            "temp_water": "temp_out1",
            "air_rh": "temprh_rh",
            "air_temp": "temprh_temp",
        },
        "properties": {
            "installation depth": -0.3,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    "70B3D5705000516A": {
        "name": "Kattilajärvi",
        "location": "Kattilaniemen leirikeskus",
        "district": "Espoo (Nuuksio)",
        "lat": 60.29904,
        "lon": 24.61975,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/39368",
        "site_url": "",
        "properties": {
            "installation depth": -0.2,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    #    '70B3D5705000E703': {
    #        'name': 'Munkkiniemi',
    #        'lat': 60.2004257,
    #        'lon': 24.8554928,
    #        'servicemap_url': 'https://palvelukartta.hel.fi/fi/unit/41601',
    #        'site_url': '',
    #    },
    "70B3D5705000E6E6": {
        "name": "Suomenlinnan uimaranta",
        "location": "Susiluodonlahti",
        "district": "Suomenlinna",
        "lat": 60.141163,
        "lon": 24.983775,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/58015",
        "site_url": "",
        "info": "Mittari pois käytöstä 7.9.2022 alkaen.",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "buoy",
            "installation method": "floating",
        },
    },
    "70B3D57050004740": {
        "name": "Lapinlahden uimaranta",
        "location": "Lapinlahti",
        "district": "Länsisatama (Lapinlahti)",
        "lat": 60.167735,
        "lon": 24.908833,
        "servicemap_url": "",
        "site_url": "",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "buoy",
            "installation method": "floating",
        },
    },
    "70B3D5705000E70E": {
        "name": "Aurinkolahden uimaranta",
        "location": "Aurinkolahti",
        "district": "Vuosaari (Aurinkolahti)",
        "lat": 60.200447,
        "lon": 25.156321,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40258",
        "site_url": "",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "buoy",
            "installation method": "floating",
        },
    },
    # "70B3D5705000E6D1": {
    #     "name": "Porvarinlahti",
    #     "location": "Porvarinlahti",
    #     "district": "Vuosaari (Niinisaari)",
    #     "lat": 60.228068,
    #     "lon": 25.185788,
    #     "servicemap_url": "",
    #     "site_url": "",
    #     "properties": {
    #         "installation depth": -0.4,
    #         "installation platform": "buoy",
    #         "installation method": "floating",
    #     },
    # },
    "70B3D5705000E6F9": {
        "name": "Arabianranta",
        "location": "Vanhankaupunginselkä",
        "district": "Toukola",
        "lat": 60.202336,
        "lon": 24.982580,
        "servicemap_url": "",
        "site_url": "",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "buoy",
            "installation method": "floating",
        },
    },
    "70B3D57050004CDB": {
        "name": "Lauttasaaren mattolaituri",
        "location": "Laukkaluoto",
        "district": "Lauttasaari (Katajaharju)",
        "lat": 60.1707,
        "lon": 24.8579,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/9266",
        "site_url": "",
        "valid_from": "2022-08-25T13:40:00Z",
        "properties": {
            "installation depth": -0.3,
            "installation platform": "pier",
            "installation method": "floating",
        },
    },
    "70B3D57050001BBC": {
        "name": "Poliisien kesäkoti",
        "location": "Länsiulapanniemi",
        "district": "Lauttasaari (Myllykallio)",
        "lat": 60.15168,
        "lon": 24.85692,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/21026",
        "site_url": "",
        "valid_from": "2022-08-29T13:30:00Z",
        "properties": {
            "installation depth": -0.28,
            "installation platform": "pier",
            "installation method": "static",
        },
    },
    # "70B3D57050004DF2": {
    #     "name": "Lauttasaaren uimaranta",
    #     "location": "",
    #     "district": "Lauttasaari",
    #     "lat": 60.15271,
    #     "lon": 24.862529,
    #     "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40098",
    #     "site_url": "",
    #     "properties": {
    #         "installation depth": -0.4,
    #         "installation platform": "buoy",
    #         "installation method": "floating",
    #     },
    # },
    # "70B3D5705000E6F2": {
    #     "name": "Lauttasaaren uimaranta",
    #     "location": "",
    #     "district": "Lauttasaari",
    #     "lat": 60.15271,
    #     "lon": 24.862529,
    #     "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40098",
    #     "site_url": "",
    # },
    # "70B3D57050001AF1": {
    #     "name": "Lauttasaari (Vaskiniemi)",
    #     "lat": 60.16050,
    #     "lon": 24.85241,
    #     "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/42212",
    #     "site_url": "https://www.sauna.fi/",
    #     "fieldmap": {
    #         "temp_water": "temp_out2",
    #         "air_temp": "temp_out1",
    #     },
    # },
    "70B3D57050004FC2": {
        "name": "Lauttasaaren ulkoilupuisto",
        "location": "Veijarivuoren puisto",
        "district": "Lauttasaari (Vattuniemi)",
        "lat": 60.14682,
        "lon": 24.89070,
        "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40701",
        "site_url": "",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    # "70B3D5705000E696": {
    #     "name": "Töölönlahti",
    #     "location": "Töölönlahti",
    #     "district": "Taka-Töölö",
    #     "lat": 60.18021,
    #     "lon": 24.9341,
    #     "servicemap_url": "",
    #     "site_url": "",
    #     "properties": {
    #         "installation depth": -0.4,
    #         "installation platform": "buoy",
    #         "installation method": "floating",
    #     },
    # },
    "70B3D5705000E653": {
        "name": "Pikku-Huopalahti",
        "location": "Pikku-Huopalahden puisto",
        "district": "Munkkiniemi (Vanha Munkkiniemi)",
        "lat": 60.197827,
        "lon": 24.890244,
        "servicemap_url": "",
        "site_url": "",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "buoy",
            "installation method": "floating",
        },
    },
    #    '70B3D57050004DF2': {
    #        'name': 'Eiranranta',
    #        'lat': 60.15241,
    #        'lon': 24.93135,
    #        'servicemap_url': '',
    #        'site_url': '',
    #    },
    "70B3D5705000E0E9": {
        "name": "Eiranranta",
        "location": "Pyhän Birgitan puisto",
        "district": "Länsisatama (Hernesaari)",
        "lat": 60.15412,
        "lon": 24.93448,
        "servicemap_url": "",
        "site_url": "",
        "valid_from": "2022-06-29T08:45:00Z",
        "properties": {
            "installation depth": -0.4,
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    # "70B3D5705000E394": {
    #     "name": "Saukonpaasi",
    #     "location": "Länsisatama",
    #     "district": "Jätkäsaari",
    #     "lat": 60.15798,
    #     "lon": 24.90376,
    #     "servicemap_url": "",
    #     "site_url": "",
    #     "valid_from": "2022-06-29T12:00:00Z",
    # },
    "70B3D57050001A97": {
        "name": "Kalasatama",
        "location": "Sompasaarensalmi",
        "district": "Sörnäinen (Sompasaari)",
        "lat": 60.180724,
        "lon": 24.979968,
        "servicemap_url": "",
        "site_url": "",
        "properties": {
            "installation depth": -0.43,  # Verified 2022-09-08
            "installation platform": "steps",
            "installation method": "static",
        },
    },
    # "003C62A8": {
    #     "name": "Uunisaari",
    #     "lat": 60.15294,
    #     "lon": 24.94991,
    #     "servicemap_url": "https://palvelukartta.hel.fi/fi/unit/40356",
    #     "site_url": "https://www.uunisaari.fi/",
    #     "fieldmap": {
    #         "temp_water": "temp_out2",
    #     },
    # },
}
